swagger: '2.0'
info:
  version: 1.0.0
  title: BankAccountTransfers
  x-ibm-name: bankaccounttransfers
host: $(catalog.host)
basePath: /apiurl
paths:
  '/bank/accounts/{AccountKey}/transactions':
    get:
      responses:
        '200':
          description: 200 OK
      parameters:
        - $ref: '#/parameters/AccountKey'
securityDefinitions:
  clientID:
    description: 'Parse the account key to content path from URI'
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - {}
x-ibm-configuration:
  assembly:
    execute:
      - gatewayscript:
          title: gatewayscript
          source: |-
            var obj='request.parameters.AccountKey';
            var objvalue=apim.getvariable(obj);
            var filobj='request.parameters.filter';
            var filobjvalue=apim.getvariable(filobj);
            var messagetoken="c:12345796js6";
            var pathContent = '{"path": "' + objvalue + '", "filter": "' + filobjvalue + '", "message": "' + messagetoken + '"}';
            apim.setvariable('genpath',pathContent,'add');
            //apim.setvariable('message.body',filobjvalue);
      - map:
          title: map
          inputs:
            input:
              schema:
                type: string
                title: input
              variable: genpath
              content: application/json
          outputs:
            output:
              schema:
                type: string
                title: output
              variable: message.body
              content: application/json
          actions:
            - set: output
              from: input
    catch: []
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  properties:
    AccountKey:
      value: ''
      description: ''
      encoded: false
  gateway: datapower-gateway
parameters:
  AccountKey:
    name: AccountKey
    type: string
    required: true
    in: path
  filter:
    name: filter
    type: string
    required: true
    in: query